query tasksWithoutrelationalData($where: TaskWhereInput, $orderBy: [TaskOrderByWithRelationInput!], $cursor: TaskWhereUniqueInput, $take: Int, $skip: Int, $distinct: [TaskScalarFieldEnum!]) {
  getUserTasks(where: $where, orderBy: $orderBy, cursor: $cursor, take: $take, skip: $skip, distinct: $distinct) {
    tags
    slug
    name
    imoji
    id
    description
    category{
      colour
    }
  }
}

query AggregateTask($where: TaskWhereInput, $cursor: TaskWhereUniqueInput) {
  aggregateTask(where: $where, cursor: $cursor) {
    _count {
      _all
    }
  }
}

  query Task($where: TaskWhereUniqueInput!) {
  task(where: $where) {
       slug
    tags

    description
    createdAt
   
    id
    imoji
    name
    updatedAt
    categoryId
    prompts {
      description
      id
      name
    }
        tips {
      id
      description
    }
     category {
      name
      colour
    }
 
  }
}

