mutation Register($input: CreateOneUserArgsCustom!) {
  register(input: $input) {
    message
  }
}

mutation Login($password: String!, $email: String!) {
  login(password: $password, email: $email) {
    accessToken
    isAuthenticated
    message
    success
    user {
      avater
      email
      id
      name
      password
      role
    }
  }
}

mutation UpdateProfile($input: UserUpdateInput!, $oldPassword: String, $updatePass: Boolean, $newPass: String, $email: String!) {
  updateProfile(input: $input, oldPassword: $oldPassword, updatePass: $updatePass, newPass: $newPass, email: $email) {
    message
  }
}